In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([
    [1,2,3],
    [4,5,6]
], index=['bob', 'alice'], columns=['f1','f2', 'f3'])
df

f1  f2  f3
bob     1   2   3
alice   4   5   6

In [3]:
df.iloc[1]

f1    4
f2    5
f3    6
Name: alice, dtype: int64

In [4]:
df.loc['alice']

f1    4
f2    5
f3    6
Name: alice, dtype: int64

In [5]:
df.loc['alice', 'f2']

5

In [6]:
f4 = df['f1'].apply(lambda v: v+10)
type(f4)

pandas.core.series.Series

In [7]:
df['f4'] = f4
df

f1  f2  f3  f4
bob     1   2   3  11
alice   4   5   6  14

In [8]:
df['f4'].unique()

array([11, 14])

In [9]:
df['f4'].value_counts()

14    1
11    1
Name: f4, dtype: int64

In [10]:
df = pd.DataFrame([
    [1,2,3],
    [4,5,6],
    [1,2,3]
])
df

0  1  2
0  1  2  3
1  4  5  6
2  1  2  3

In [11]:
df = pd.DataFrame([
    [1,2,3],
    [4,5,6],
    [1,2,7]
])
df

0  1  2
0  1  2  3
1  4  5  6
2  1  2  7

In [12]:
df.drop_duplicates(subset=[0,1]) # 只看第一、二列

0  1  2
0  1  2  3
1  4  5  6

In [13]:
df1 = df.T
df1

0  1  2
0  1  4  1
1  2  5  2
2  3  6  7

In [14]:
# method 1
corrs = df.corr().abs()
corrs

0        1        2
0  1.00000  1.00000  0.27735
1  1.00000  1.00000  0.27735
2  0.27735  0.27735  1.00000

In [15]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# One-hot encoder
# 0 => 000
# 1 => 001
# 2 => 010

# fit
X = np.array([[0,1,2,0,1,2]]).T
enc = OneHotEncoder(sparse=False)
enc.fit(X) # learn

OneHotEncoder(sparse=False)

In [16]:
# transform
X1 = np.array([[0,1,2,0,1,2]]).T
enc.transform(X1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# fit & transform
enc.fit_transform(X)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])